import './style.css';
import { AppThemeProvider } from '@/shared/Providers/themeProvider';

import { CssBaseline } from '@mui/material';
import type { Metadata } from 'next';

import '@fontsource/bree-serif/400.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppThemeProvider>
          <CssBaseline />
          {children}
        </AppThemeProvider>
      </body>
    </html>
  );
}
